name: server

on:
  # workflow_run:
  #   workflows: ["docker"]
  #   types:
  #     - completed
  workflow_dispatch:
  pull_request:

jobs:
  server:
    runs-on: self-hosted
    steps:
      - name: SSH Action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /home/$USER/Projects/Book
            git pull
            docker-compose down
            docker rmi mraddict063/book
            docker-compose up -d
